services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: clutch_academy
    ports:
      - "5432:5432"
  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: ${SERVICE_PROFILE}
    ports:
      - "8080:8080"